version: '3.5'
services:
  ##Laisser le nom main pour la localisation des folder pour la resolution du path de config
  timer:
    build:
      context: .
      dockerfile: ./timer/Dockerfile-alpine
    container_name: timer
    image: semanticbus/timer
    environment:
        - APP_PORT=100
        - NODE_ENV=development_docker
        - CONFIG_URL=$CONFIG_URL
    volumes:
      - ./timer:/data/timer/
      - ./core:/data/core/
    networks:
      - bus
    ports:
      - "100:100"
    expose:
      - "100"
    links:
        - mongodb
        - rabbitmq
    depends_on:
        - mongodb
        - rabbitmq
    command: ["/data/scripts/wait-for-it.sh", "rabbitmq:5672", "-t", "25", "--", "nodemon", "-L", "--watch", "/data/timer/*",  "--watch", "/data/core/*",  "--ignore", "configuration.js",  "/data/timer/app.js"]

  engine:
    build:
      context: .
      dockerfile: ./engine/Dockerfile-alpine
    container_name: engine
    environment:
        - APP_PORT=90
        - NODE_ENV=development_docker
        - CONFIG_URL=$CONFIG_URL
    volumes:
      - ./engine:/data/engine/
      - ./core:/data/core/
    networks:
      - bus
    ports:
      - "90:90"
    expose:
      - "90"
    links:
        - mongodb
        - rabbitmq
    depends_on:
        - mongodb
        - rabbitmq
    command: bash -c "/data/scripts/wait-for-it.sh rabbitmq:5672 -t 60 -- nodemon --watch /data/engine --watch /data/core --ignore configuration.js --max-old-space-size=4096 /data/engine/app.js"


  main:
    build:
      context: .
      dockerfile: ./main/Dockerfile-alpine
    container_name: main
    image: semanticbus/main
    environment:
        - APP_PORT=80
        - NODE_ENV=development_docker
        - CONFIG_URL=$CONFIG_URL
    volumes:
      - ./main:/data/main/
      - ./core:/data/core/
    networks:
      - bus
    ports:
      - "80:80"
    expose:
      - "80"
    links:
        - mongodb
        - rabbitmq
    depends_on:
        - mongodb
        - rabbitmq
    command: ["/data/scripts/wait-for-it.sh", "rabbitmq:5672", "-t", "25", "--", "nodemon", "-L", "--watch", "/data/main/*",  "--watch", "/data/core/*",  "--ignore", "configuration.js", "--max-old-space-size=8192",  "/data/main/app.js"]

  rabbitmq:
    image: semanticbus/rabbitmq-stomp
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15674:15674
      - 15672:15672
    networks:
      - bus

  mongodb:
    image: mongo:4.0.6
    networks:
      - bus
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - data:/data/db
    command: --smallfiles

volumes:
  data:

networks:
  bus:
    name: bus_network
    # external: true
