FROM node:12.13-alpine

WORKDIR /data/engine

# confirm installation
RUN node -v
RUN npm -v

ARG CONFIG_URL
ARG PM2_PUBLIC_KEY
ARG PM2_SECRET_KEY
ARG ENV

RUN if [ "$ENV" == "production" ]; \
    then  npm install -g pm2 2> /dev/null; \
    else  npm install nodemon -g 2> /dev/null; \
    fi

ENV CONFIG_URL=$CONFIG_URL
ENV PM2_PUBLIC_KEY=$PM2_PUBLIC_KEY
ENV PM2_SECRET_KEY=$PM2_SECRET_KEY
ENV BROADCAST_LOGS 1
ENV FORCE_INSPECTOR 1

# install tool for npm lib compile in C
RUN apk add --update --no-cache autoconf libtool automake python alpine-sdk

# Install app dependencies
COPY ./engine/package.json /data/

RUN cd /data/ && npm cache clean --force && npm install --loglevel verbose

# add src & build configuraiton
COPY ./core /data/core/
COPY ./engine /data/engine/

COPY ./wait-for-it.sh /data/scripts/

# Expose ports (for orchestrators and dynamic reverse proxies)
EXPOSE 8080

CMD [ "pm2-runtime", "app.js", "--name" ,"main"]
