# defaultEntryPoints must be at the top 
# because it should not be in any table below
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http", "wss", "ws"]

# Entrypoints
[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]

[api]
# Port for the status page
address = ":8080"    

# Let's Encrypt settings
[acme]
email = "semanticbusdev@gmail.com"
storage = "/acme.json"
entryPoint = "https"
acmeLogging = true
onDemand = false
onHostRule = true
[acme.httpChallenge]
  entryPoint = "http"
# Let's Encrypt domains
[[acme.domains]]
main = "*.semantic-bus.org"

# Reload is file modified
watch = true