# defaultEntryPoints must be at the top 
# because it should not be in any table below
debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]

# http should be redirected to https
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"

# https is the default
[entryPoints.https]
address = ":443"
[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "semantic-bus.org"
watch = true
exposedByDefault = true

[acme]
email = "semanticbusdev@gmail.com"
storage = "/traefik/acme/account"
storageFile = "/acme.json"
entryPoint = "https"
[acme.httpChallenge]
  entryPoint = "http"
OnHostRule = true
[[acme.domains]]
  main = "*.semantic-bus.org"
[[acme.domains]]
  main = "test2.semantic-bus.org"

