version: '3.0'
services:         
  
  stripe:
    build:
      context: .
      dockerfile: ./main/Dockerfile
    container_name: semanticbus
    image: debian/latest
    environment:
        - APP_PORT=80
        - NODE_ENV=development_docker
        - CONFIG_URL=https://data-players.github.io/StrongBox/private/micro-service-prod.json
    networks:
      - back  
    ports:
      - "80:80"
    expose:
      - "80"
    links:
        - mongodb
    depends_on:
        - mongodb
      
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - back  
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - data:/data/db
    command: --smallfiles

volumes:
  data:

networks: 
  back: 