module.exports = {

    // -------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------
    // --------------------------------------------------------------------------------

    restGetJson: require('../workspaceComponentExecutor/restGetJson.js'),
    objectTransformer: require('../workspaceComponentExecutor/objectTransformer.js'),
    googleGetJson: require('../workspaceComponentExecutor/googleGetJson.js'),
    simpleAgregator: require('../workspaceComponentExecutor/simpleAgregator.js'),
    googleGeoLocaliser: require('../workspaceComponentExecutor/googleGeoLocaliser.js'),
    cacheNosql: require('../workspaceComponentExecutor/cacheNosql.js'),
    gouvFrInverseGeo: require('../workspaceComponentExecutor/gouvFrInverseGeo.js'),
    restApiGet: require('../workspaceComponentExecutor/restApiGet.js'),
    restApiPost: require('../workspaceComponentExecutor/restApiPost.js'),
    // xmlToObject: require('./workspaceComponentExecutor/xmlToObject.js'),
    framcalcGetCsv: require('../workspaceComponentExecutor/framcalcGetCsv.js'),
    gouvFrGeoLocaliser: require('../workspaceComponentExecutor/gouvFrGeoLocaliser.js'),
    // gouvFrGeoLocaliserMass: require('./workspaceComponentExecutor/gouvFrGeoLocaliserMass.js'),
    joinByField: require('../workspaceComponentExecutor/joinByField.js'),
    deeperFocusOpeningBracket: require('../workspaceComponentExecutor/deeperFocusOpeningBracket.js'),
    filter: require('../workspaceComponentExecutor/filter.js'),
    upload: require('../workspaceComponentExecutor/upload.js'),
    scrapper: require('../workspaceComponentExecutor/scrapper/scrapper.js'),
    httpGet: require('../workspaceComponentExecutor/restGetFile.js'),
    sqlConnector: require('../workspaceComponentExecutor/sqlConnecteur.js'),
    mongoConnector: require('../workspaceComponentExecutor/MongoDB.js'),
    influxdbConnector: require('../workspaceComponentExecutor/influxdb.js'),
    sparqlRequest: require('../workspaceComponentExecutor/sparqlRequest.js'),
    valueMapping: require('../workspaceComponentExecutor/valueMapping.js'),
    timer: require('../workspaceComponentExecutor/timer.js'),
    queryParamsCreation: require('../workspaceComponentExecutor/queryParamsCreation.js'),
    valueFromPath: require('../workspaceComponentExecutor/valueFromPath.js'),
    unicity: require('../workspaceComponentExecutor/unicity.js'),
    propertiesMatrix: require('../workspaceComponentExecutor/propertiesMatrix.js'),
    postConsumer: require('../workspaceComponentExecutor/postConsumer.js'),
    keyToArray: require('../workspaceComponentExecutor/keyToArray.js'),
    sftpConsumer: require('../workspaceComponentExecutor/sftpConsumer.js'),
    flat: require('../workspaceComponentExecutor/flat.js'),
    jsEvaluation: require('../workspaceComponentExecutor/jsEvaluation.js'),
    slugify: require('../workspaceComponentExecutor/slugify.js'),
    regex: require('../workspaceComponentExecutor/regex.js'),
    split: require('../workspaceComponentExecutor/split.js'),
    // ---ENDOFPART---
}