name: CI/CD Pipeline

on:
  push:
    branches: [ master, main, develop, dependency-update-and-quality-control ]

jobs:
  test-unit:
    name: Tests - ${{ matrix.module }} (Node ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        module: [core, main, engine, timer]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'packages/${{ matrix.module }}/package-lock.json'
        
    - name: Install dependencies for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm ci
      
    - name: Run tests for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm test
      
    - name: Upload coverage reports for ${{ matrix.module }}
      if: matrix.module == 'engine'
      uses: codecov/codecov-action@v3
      with:
        directory: ./packages/engine/coverage
        fail_ci_if_error: false

  # Integration tests removed - handled per module in test-unit job

  # test-e2e:
  #   name: E2E Tests
  #   runs-on: ubuntu-latest
  #   needs: [test-unit, test-integration]
  #   
  #   services:
  #     mongodb:
  #       image: mongo:4.0.6
  #       ports:
  #         - 27017:27017
  #       options: >-
  #         --health-cmd "echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet"
  #         --health-interval 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #         
  #     rabbitmq:
  #       image: semanticbus/rabbitmq-stomp
  #       ports:
  #         - 5672:5672
  #         - 15674:15674
  #         - 15672:15672
  #       options: >-
  #         --health-cmd "rabbitmq-diagnostics -q ping"
  #         --health-interval 30s
  #         --health-timeout 30s
  #         --health-retries 3
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '20.x'
  #       cache: 'npm'
  #       
  #   - name: Install dependencies
  #     run: npm run install:all
  #     
  #   - name: Wait for services
  #     run: |
  #       echo "Waiting for MongoDB..."
  #       timeout 60 bash -c 'until nc -z localhost 27017; do sleep 1; done'
  #       echo "Waiting for RabbitMQ..."
  #       timeout 60 bash -c 'until nc -z localhost 5672; do sleep 1; done'
  #       
  #   - name: Setup Docker Buildx
  #     uses: docker/setup-buildx-action@v3
  #     
  #   - name: Build test environment
  #     run: make test-build
  #     
  #   - name: Run E2E tests
  #     run: make test-start

  lint:
    name: Linting - ${{ matrix.module }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        module: [main, engine]  # Only modules that have lint script
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'packages/${{ matrix.module }}/package-lock.json'
        
    - name: Install dependencies for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm ci
        
    - name: Run linting for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm run lint

  # Security audit moved to dependency-quality-control.yml to avoid duplication

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [test-unit, lint]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build and push Docker images
      run: |
        make docker-build
        # Add docker push commands if needed
        
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to production
      run: |
        echo "Deployment step - configure according to your deployment strategy"
        # Add deployment commands here