name: Module Tests & Quality

on:
  push:
    branches: [ master, main, develop, dependency-update-and-quality-control ]

jobs:
  tests:
    name: Tests - ${{ matrix.module }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        module: [core, main, engine, timer]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'packages/${{ matrix.module }}/package-lock.json'
        
    - name: Install dependencies for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm ci
        
    - name: Run tests for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm test
    
    # Security audit moved to dependency-quality-control.yml to avoid duplication

  linting:
    name: Linting - ${{ matrix.module }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        module: [main, engine]  # Only modules that have lint script
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'packages/${{ matrix.module }}/package-lock.json'
        
    - name: Install dependencies for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm ci
        
    - name: Run linting for ${{ matrix.module }}
      run: |
        cd packages/${{ matrix.module }}
        npm run lint

  code-quality:
    name: Code Coverage - Engine
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'packages/engine/package-lock.json'
        
    - name: Install dependencies for engine
      run: |
        cd packages/engine
        npm ci
      
    - name: Generate test coverage for engine
      run: |
        cd packages/engine
        npm run test:coverage
        
          # No PR comments since this workflow only runs on push events

  dependency-check:
    name: Dependency Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Check for outdated dependencies
      run: |
        echo "Checking for outdated dependencies..."
        cd packages/engine && npm outdated || true
        cd ../main && npm outdated || true
        cd ../timer && npm outdated || true
        cd ../core && npm outdated || true
        
    - name: Check module package-lock.json changes
      run: |
        if git diff --name-only HEAD^ | grep -q "*/package-lock.json"; then
          echo "⚠️ Module package-lock.json files have been modified"
          echo "Please ensure dependencies are properly reviewed in affected modules"
        fi